name: build and release-please

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      ACTION_NAME: auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git pull
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: commit
        run: |-
          set -e
          # get current commit hash
          CURRENT_HASH=$(git rev-parse HEAD)
          # get last commit hash of last build dist
          LAST_BUILD_HASH=$(git log --author=google-github-actions-bot -1 --pretty=format:"%H")
          DIFF=""
          # build and commit dist if diff
          git config --global user.name "actions-bot"
          git config user.email 'github-actions-bot@google.com'
          git add dist/
          git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
          if [ -z "$LAST_BUILD_HASH" ]
          then
                echo "Unable to find last commit by bot, skipping diff gen"
          else
                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
                echo $DIFF
          fi
          # set env vars
          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          echo "${DIFF}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          commit-message: Build dist
          author: "actions-bot <github-actions-bot@google.com>"
          title: "chore: build dist"
          body: |
            Build dist PR
            ${{env.DIFF}}
          labels: automated pr
          branch: create-pull-request/build-dist
          delete-branch: true
          push-to-fork: google-github-actions-bot/${{env.ACTION_NAME}}
  release-please-pr:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
          fork: true
          package-name: ${{env.ACTION_NAME}}
          command: release-pr
  release-please-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: google-github-actions/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
          package-name: ${{env.ACTION_NAME}}
          command: github-release
